import { defineConfig, globalIgnores } from "eslint/config";
import { node } from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  globalIgnores([
    "eslint.config.ts",
    "webpack.config.ts",
    "node_modules/*",
    "dist/*",
    "tests/*",
    "coverage/*",
  ]),

  ...tseslint.configs.recommended,

  {
    files: ["**/*.ts"],
    languageOptions: {
      parser: tseslint.parser,
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...node,
        myCustomGlobal: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      "no-undef": "off",
      "class-methods-use-this": "off",

      "no-underscore-dangle": "error",

      "array-callback-return": "error",
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": [
        "error",
        {
          checkLoops: "allExceptWhileTrue",
        },
      ],
      "no-constructor-return": "error",
      "no-control-regex": "error",
      "no-debugger": "warn",
      "no-dupe-args": "off",
      "no-dupe-class-members": "off",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "off",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-ex-assign": "error",
      "no-fallthrough": [
        "error",
        {
          commentPattern: "fallthrough",
        },
      ],
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-inner-declarations": ["error", "both"],
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": [
        "error",
        {
          allowEscape: true,
        },
      ],
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-setter-return": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-this-before-super": "error",
      "no-unassigned-vars": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unreachable": "off",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-private-class-members": "error",
      "no-use-before-define": "off",
      "@typescript-eslint/no-use-before-define": "error",
      "no-useless-assignment": "error",
      "require-atomic-updates": "error",
      "use-isnan": "error",

      "block-scoped-var": "error",
      complexity: [
        "error",
        {
          max: 5,
        },
      ],
      "max-depth": [
        "error",
        {
          max: 3,
        },
      ],
      "max-classes-per-file": "error",
      "max-lines": [
        "error",
        {
          max: 300,
          skipBlankLines: true,
          skipComments: true,
        },
      ],
      "max-params": [
        "error",
        {
          max: 3,
          countThis: "except-void",
        },
      ],
      "max-lines-per-function": [
        "error",
        {
          max: 10,
          skipBlankLines: true,
          skipComments: true,
        },
      ],

      "no-alert": "error",
      "no-eval": "error",
      "no-extra-bind": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implied-eval": "error",
      "no-lonely-if": "error",
      "no-magic-numbers": [
        "error",
        {
          ignoreArrayIndexes: true,
          ignoreClassFieldInitialValues: true,
          ignoreEnums: true,
          ignoreReadonlyClassProperties: true,
          ignoreTypeIndexes: true,
        },
      ],
      "no-nested-ternary": "error",
      "no-proto": "error",
      "no-param-reassign": "error",
      "no-octal-escape": "error",
      "no-octal": "error",
      "no-object-constructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-new-wrappers": "error",
      "no-new-func": "error",
      "no-new": "error",
      "prefer-object-has-own": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "error",
      "no-with": "error",
      "no-var": "error",
      "no-useless-return": "error",
      "no-useless-rename": "error",
      "no-useless-escape": "error",
      "no-useless-concat": "error",
      "no-useless-computed-key": "error",
      "no-useless-catch": "error",
      "no-useless-call": "error",
      "no-unused-expressions": "off",
      "@typescript-eslint/no-unused-expressions": "error",
      "no-unneeded-ternary": "error",
      "no-undefined": "error",
      "no-undef-init": "error",
      "no-throw-literal": "off",
      "@typescript-eslint/only-throw-error": "error",
      "no-shadow-restricted-names": "error",
      "no-sequences": "error",
      "no-script-url": "error",
      "no-return-assign": "error",
      "no-regex-spaces": "error",
      "prefer-template": "error",
      "preserve-caught-error": "error",
      "require-await": "off",
      "@typescript-eslint/require-await": "error",
      "require-yield": "error",
    },
  },
]);
